apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
  annotations:
    description: "Armazena credenciais sensíveis do MySQL"
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VuaGFNdWl0b0luY3JpdmVs